apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaservice-deployment
spec:
  replicas: 1   # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mediaserviceaks
  template:
    metadata:
      labels:
        app: mediaserviceaks
    spec:
      containers:
      - name: infallible-dubinsky
        image: zakaria469980/mediaservice:latest
        ports:
        - containerPort: 80   # Adjust the port number as needed
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: mediaserviceaks
  ports:
    - name: http-port
      protocol: TCP
      port: 5117
      targetPort: 80
    - name: https-port
      protocol: TCP
      port: 7117
      targetPort: 443   # Adjust the target port as needed
  type: LoadBalancer   # Use NodePort, ClusterIP, or LoadBalancer based on your setup
