apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediaservice
  template:
    metadata:
      labels:
        app: mediaservice
    spec:
      containers:
        - name: mediaservice
          image: zakaria469980/newestmediaservice:latest
          ports:
            - containerPort: 5118
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: mediaservice  # Adjusted to match the correct label
  ports:
    - protocol: TCP
      port: 5118
      targetPort: 81
      name: http-port
    - protocol: TCP
      port: 7117
      targetPort: 443
      name: https-port
    - name: postgres 
      protocol: TCP
      port: 5433
      targetPort: 5433
  type: LoadBalancer




# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mediaservice
# spec:
#   type: NodePort
#   selector:
#     app: mediaservice
#   ports:
#     - name: mediaservice
#       protocol: TCP
#       port: 80
#       targetPort: 80