apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaservice-deployment
spec:
  replicas: 1   # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mediaservice
  template:
    metadata:
      labels:
        app: mediaservice
    spec:
      containers:
        - name: mediaservice
          image: zakaria469980/mediaservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mediaservice
spec:
  type: NodePort
  selector:
    app: mediaservice
  ports:
    - name: mediaservice
      protocol: TCP
      port: 80
      targetPort: 80

