apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
spec:
  replicas: 1   # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
      - name: infallible-dubinsky
        image: zakaria469980/mediaservice:latest
        ports:
        - containerPort: 5116   # Adjust the port number as needed
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media-service
  ports:
    - protocol: TCP
      port: 5116
      targetPort: 80
      name: http-port
    - protocol: TCP
      port: 7117
      targetPort: 443   # Adjust the target port as needed
      name: https-port
  type: LoadBalancer   # Use NodePort, ClusterIP, or LoadBalancer based on your setup
