apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-media-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydatabase
          ports:
            - containerPort: 5433
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-media
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5433
      targetPort: 5433
