apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-media-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediaservice
  template:
    metadata:
      labels:
        app: mediaservice
    spec:
      containers:
        - name: postgres-media
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydatabase
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5433
          volumeMounts:
            - name: media-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: postgres-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-media
spec:
  selector:
    app: mediaservice
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
