name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0' # or the version you need

    - name: Build
      run: |
        cd "C:/Users/ZAHas/source/repos/Semester 6 GIT/FootTweets/MediaService/MediaService"
        dotnet build MediaService.csproj

